//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Vendor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Vendor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Vendor", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories Stylist.
        /// </summary>
        internal static string Categories_Vendor {
            get {
                return ResourceManager.GetString("Categories_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give Review.
        /// </summary>
        internal static string Give_Review {
            get {
                return ResourceManager.GetString("Give_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your review for Stylist.
        /// </summary>
        internal static string Give_your_review_for_vendor {
            get {
                return ResourceManager.GetString("Give_your_review_for_vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string Invalid_Password {
            get {
                return ResourceManager.GetString("Invalid_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Stylist.
        /// </summary>
        internal static string Latest_Vendors {
            get {
                return ResourceManager.GetString("Latest_Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberShip.
        /// </summary>
        internal static string MemberShip {
            get {
                return ResourceManager.GetString("MemberShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your messages sent to stylist. Thank you very much.
        /// </summary>
        internal static string messages_sent_success {
            get {
                return ResourceManager.GetString("messages_sent_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order for Stylist.
        /// </summary>
        internal static string New_Order_for_Vendor {
            get {
                return ResourceManager.GetString("New_Order_for_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password have 6 to 20 characters string with at least one digit, one upper case letter, one lower case letter and one special symbol @, #, $, %.
        /// </summary>
        internal static string Password_validate_message {
            get {
                return ResourceManager.GetString("Password_validate_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Success.
        /// </summary>
        internal static string Payment_Success {
            get {
                return ResourceManager.GetString("Payment_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Invalid.
        /// </summary>
        internal static string Photo_Invalid {
            get {
                return ResourceManager.GetString("Photo_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products are available.
        /// </summary>
        internal static string products_are_available {
            get {
                return ResourceManager.GetString("products_are_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products of Vendor.
        /// </summary>
        internal static string Products_of_Vendor {
            get {
                return ResourceManager.GetString("Products_of_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Messages to.
        /// </summary>
        internal static string Send_Messages_to {
            get {
                return ResourceManager.GetString("Send_Messages_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Messages to Stylist.
        /// </summary>
        internal static string Send_Messages_to_Vendor {
            get {
                return ResourceManager.GetString("Send_Messages_to_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists.
        /// </summary>
        internal static string Username_already_exists {
            get {
                return ResourceManager.GetString("Username_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylist does not exist.
        /// </summary>
        internal static string Vendor_does_not_exist {
            get {
                return ResourceManager.GetString("Vendor_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylist Info.
        /// </summary>
        internal static string Vendor_Info {
            get {
                return ResourceManager.GetString("Vendor_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylist Information.
        /// </summary>
        internal static string Vendor_Information {
            get {
                return ResourceManager.GetString("Vendor_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylist Panel.
        /// </summary>
        internal static string Vendor_Panel {
            get {
                return ResourceManager.GetString("Vendor_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylist Register.
        /// </summary>
        internal static string Vendor_Register {
            get {
                return ResourceManager.GetString("Vendor_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your review sent to Stylist. Thanks you very much.
        /// </summary>
        internal static string Your_review_sent_to_vendor {
            get {
                return ResourceManager.GetString("Your_review_sent_to_vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be customer before give review.
        /// </summary>
        internal static string You_must_be_customer {
            get {
                return ResourceManager.GetString("You_must_be_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need login before send message.
        /// </summary>
        internal static string You_need_login {
            get {
                return ResourceManager.GetString("You_need_login", resourceCulture);
            }
        }
    }
}
